fix: cleanup runtime default properties on first reconcile, fixes RHOAIENG-15033
opendatahub-io/model-registry-operator pull request #158
Opened 2024-11-05 06:31 UTC by dhirajsb

## Description

Cleanup runtime default properties on first reconcile
Fixes RHOAIENG-15033

## How Has This Been Tested?

Tested locally by using an MR with default runtime properties and verified that it gets cleaned up to remove them.

Create test MR using secure-db mysql-tls sample, then delete the test MR and recreate using the command:
```shell
oc delete mr -n odh-model-registries
oc apply -f - <<EOF
apiVersion: modelregistry.opendatahub.io/v1alpha1
kind: ModelRegistry
metadata:
  labels:
    app.kubernetes.io/created-by: model-registry-operator
    app.kubernetes.io/instance: modelregistry-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: modelregistry
    app.kubernetes.io/part-of: model-registry-operator
  name: modelregistry-sample
  namespace: odh-model-registries
spec:
  grpc:
    image: quay.io/opendatahub/mlmd-grpc-server:latest
    port: 9090
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 256Mi
  istio:
    authProvider: opendatahub-auth-provider
    authConfigLabels:
      security.opendatahub.io/authorization-group: default
    gateway:
      grpc:
        gatewayRoute: enabled
        port: 443
        tls:
          credentialName: default-modelregistry-cert
          mode: SIMPLE
      istioIngress: ingressgateway
      rest:
        gatewayRoute: enabled
        port: 443
        tls:
          credentialName: default-modelregistry-cert
          mode: SIMPLE
    tlsMode: ISTIO_MUTUAL
  mysql:
    database: model_registry
    host: model-registry-db
    passwordSecret:
      key: database-password
      name: model-registry-db
    port: 3306
    skipDBCreation: false
    sslRootCertificateConfigMap:
      key: ca.crt
      name: model-registry-db-credential
    username: mlmduser
  rest:
    image: quay.io/opendatahub/model-registry:latest
    port: 8080
    serviceRoute: disabled
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 256Mi
EOF
```

After reconciliation with this fix, the default runtime property values including images should be removed from the above MR. 

## Merge criteria:

- [X] The commits and have meaningful messages; the author will squash them [after approval](https://github.com/opendatahub-io/opendatahub-community/blob/main/contributor-cheatsheet.md#:~:text=Usually%20this%20is%20done%20in%20last%20phase%20of%20a%20PR%20revision) or will ask to merge with squash.
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has manually tested the changes and verified that the changes work

2024-11-06 11:04 UTC, Al-Pragliola requested changes

2024-11-06 11:04 UTC, Al-Pragliola commented on api/v1alpha1/modelregistry_webhook.go
> +				(r.Spec.Istio.Gateway.Grpc.TLS.CredentialName != nil || *r.Spec.Istio.Gateway.Grpc.TLS.CredentialName == config.GetDefaultCert()) {
```suggestion
				(r.Spec.Istio.Gateway.Grpc.TLS.CredentialName != nil && *r.Spec.Istio.Gateway.Grpc.TLS.CredentialName == config.GetDefaultCert()) {
```

2024-11-06 20:02 UTC, dhirajsb commented on api/v1alpha1/modelregistry_webhook.go
> +				(r.Spec.Istio.Gateway.Grpc.TLS.CredentialName != nil || *r.Spec.Istio.Gateway.Grpc.TLS.CredentialName == config.GetDefaultCert()) {
good catch, fixed :pray:

2024-11-07 11:40 UTC, Al-Pragliola approved these changes
lgtm

2024-11-08 10:53 UTC, Al-Pragliola approved these changes

2024-11-08 10:53 UTC, merged